// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: api/bookings_api/bookings.proto

package bookings_api

import (
	context "context"
	models "github.com/Domenick1991/airbooking/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightId   int64  `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SeatNumber int32  `protobuf:"varint,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bookings_api_bookings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookings_api_bookings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_bookings_api_bookings_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetFlightId() int64 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *CreateBookingRequest) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

func (x *CreateBookingRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BookingTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *BookingTokenRequest) Reset() {
	*x = BookingTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bookings_api_bookings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingTokenRequest) ProtoMessage() {}

func (x *BookingTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bookings_api_bookings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingTokenRequest.ProtoReflect.Descriptor instead.
func (*BookingTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_bookings_api_bookings_proto_rawDescGZIP(), []int{1}
}

func (x *BookingTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_bookings_api_bookings_proto protoreflect.FileDescriptor

var file_api_bookings_api_bookings_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2b, 0x0a, 0x13, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x88, 0x03, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x2e, 0x61,
	0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x69,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22,
	0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x73, 0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x1a, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x7b, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x2a, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x7d, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x44, 0x6f, 0x6d, 0x65, 0x6e, 0x69, 0x63, 0x6b, 0x31, 0x39, 0x39, 0x31, 0x2f, 0x61, 0x69,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x3b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_bookings_api_bookings_proto_rawDescOnce sync.Once
	file_api_bookings_api_bookings_proto_rawDescData = file_api_bookings_api_bookings_proto_rawDesc
)

func file_api_bookings_api_bookings_proto_rawDescGZIP() []byte {
	file_api_bookings_api_bookings_proto_rawDescOnce.Do(func() {
		file_api_bookings_api_bookings_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_bookings_api_bookings_proto_rawDescData)
	})
	return file_api_bookings_api_bookings_proto_rawDescData
}

var file_api_bookings_api_bookings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_bookings_api_bookings_proto_goTypes = []interface{}{
	(*CreateBookingRequest)(nil), // 0: airbooking.bookings_api.CreateBookingRequest
	(*BookingTokenRequest)(nil),  // 1: airbooking.bookings_api.BookingTokenRequest
	(*models.Booking)(nil),       // 2: airbooking.models.Booking
}
var file_api_bookings_api_bookings_proto_depIdxs = []int32{
	0, // 0: airbooking.bookings_api.BookingsService.CreateBooking:input_type -> airbooking.bookings_api.CreateBookingRequest
	1, // 1: airbooking.bookings_api.BookingsService.ConfirmBooking:input_type -> airbooking.bookings_api.BookingTokenRequest
	1, // 2: airbooking.bookings_api.BookingsService.CancelBooking:input_type -> airbooking.bookings_api.BookingTokenRequest
	2, // 3: airbooking.bookings_api.BookingsService.CreateBooking:output_type -> airbooking.models.Booking
	2, // 4: airbooking.bookings_api.BookingsService.ConfirmBooking:output_type -> airbooking.models.Booking
	2, // 5: airbooking.bookings_api.BookingsService.CancelBooking:output_type -> airbooking.models.Booking
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_bookings_api_bookings_proto_init() }
func file_api_bookings_api_bookings_proto_init() {
	if File_api_bookings_api_bookings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_bookings_api_bookings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bookings_api_bookings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_bookings_api_bookings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bookings_api_bookings_proto_goTypes,
		DependencyIndexes: file_api_bookings_api_bookings_proto_depIdxs,
		MessageInfos:      file_api_bookings_api_bookings_proto_msgTypes,
	}.Build()
	File_api_bookings_api_bookings_proto = out.File
	file_api_bookings_api_bookings_proto_rawDesc = nil
	file_api_bookings_api_bookings_proto_goTypes = nil
	file_api_bookings_api_bookings_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookingsServiceClient is the client API for BookingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingsServiceClient interface {
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*models.Booking, error)
	ConfirmBooking(ctx context.Context, in *BookingTokenRequest, opts ...grpc.CallOption) (*models.Booking, error)
	CancelBooking(ctx context.Context, in *BookingTokenRequest, opts ...grpc.CallOption) (*models.Booking, error)
}

type bookingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingsServiceClient(cc grpc.ClientConnInterface) BookingsServiceClient {
	return &bookingsServiceClient{cc}
}

func (c *bookingsServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*models.Booking, error) {
	out := new(models.Booking)
	err := c.cc.Invoke(ctx, "/airbooking.bookings_api.BookingsService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) ConfirmBooking(ctx context.Context, in *BookingTokenRequest, opts ...grpc.CallOption) (*models.Booking, error) {
	out := new(models.Booking)
	err := c.cc.Invoke(ctx, "/airbooking.bookings_api.BookingsService/ConfirmBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) CancelBooking(ctx context.Context, in *BookingTokenRequest, opts ...grpc.CallOption) (*models.Booking, error) {
	out := new(models.Booking)
	err := c.cc.Invoke(ctx, "/airbooking.bookings_api.BookingsService/CancelBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingsServiceServer is the server API for BookingsService service.
type BookingsServiceServer interface {
	CreateBooking(context.Context, *CreateBookingRequest) (*models.Booking, error)
	ConfirmBooking(context.Context, *BookingTokenRequest) (*models.Booking, error)
	CancelBooking(context.Context, *BookingTokenRequest) (*models.Booking, error)
}

// UnimplementedBookingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookingsServiceServer struct {
}

func (*UnimplementedBookingsServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*models.Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (*UnimplementedBookingsServiceServer) ConfirmBooking(context.Context, *BookingTokenRequest) (*models.Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmBooking not implemented")
}
func (*UnimplementedBookingsServiceServer) CancelBooking(context.Context, *BookingTokenRequest) (*models.Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBooking not implemented")
}

func RegisterBookingsServiceServer(s *grpc.Server, srv BookingsServiceServer) {
	s.RegisterService(&_BookingsService_serviceDesc, srv)
}

func _BookingsService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbooking.bookings_api.BookingsService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_ConfirmBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).ConfirmBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbooking.bookings_api.BookingsService/ConfirmBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).ConfirmBooking(ctx, req.(*BookingTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbooking.bookings_api.BookingsService/CancelBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).CancelBooking(ctx, req.(*BookingTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "airbooking.bookings_api.BookingsService",
	HandlerType: (*BookingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _BookingsService_CreateBooking_Handler,
		},
		{
			MethodName: "ConfirmBooking",
			Handler:    _BookingsService_ConfirmBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _BookingsService_CancelBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bookings_api/bookings.proto",
}
