// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: api/flights_api/flights.proto

package flights_api

import (
	context "context"
	models "github.com/Domenick1991/airbooking/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFlightRequest) Reset() {
	*x = GetFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_flights_api_flights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightRequest) ProtoMessage() {}

func (x *GetFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flights_api_flights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightRequest.ProtoReflect.Descriptor instead.
func (*GetFlightRequest) Descriptor() ([]byte, []int) {
	return file_api_flights_api_flights_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlightRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListFlightsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*models.Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *ListFlightsResponse) Reset() {
	*x = ListFlightsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_flights_api_flights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlightsResponse) ProtoMessage() {}

func (x *ListFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_flights_api_flights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlightsResponse.ProtoReflect.Descriptor instead.
func (*ListFlightsResponse) Descriptor() ([]byte, []int) {
	return file_api_flights_api_flights_proto_rawDescGZIP(), []int{1}
}

func (x *ListFlightsResponse) GetFlights() []*models.Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type GetFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *models.Flight `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
}

func (x *GetFlightResponse) Reset() {
	*x = GetFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_flights_api_flights_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightResponse) ProtoMessage() {}

func (x *GetFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_flights_api_flights_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightResponse.ProtoReflect.Descriptor instead.
func (*GetFlightResponse) Descriptor() ([]byte, []int) {
	return file_api_flights_api_flights_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlightResponse) GetFlight() *models.Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

var File_api_flights_api_flights_proto protoreflect.FileDescriptor

var file_api_flights_api_flights_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x66, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x07,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x32,
	0xfd, 0x01, 0x0a, 0x0e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2b, 0x2e, 0x61, 0x69, 0x72, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12,
	0x7e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x2e, 0x61,
	0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x69, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42,
	0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x6f,
	0x6d, 0x65, 0x6e, 0x69, 0x63, 0x6b, 0x31, 0x39, 0x39, 0x31, 0x2f, 0x61, 0x69, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x62, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x3b, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_flights_api_flights_proto_rawDescOnce sync.Once
	file_api_flights_api_flights_proto_rawDescData = file_api_flights_api_flights_proto_rawDesc
)

func file_api_flights_api_flights_proto_rawDescGZIP() []byte {
	file_api_flights_api_flights_proto_rawDescOnce.Do(func() {
		file_api_flights_api_flights_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_flights_api_flights_proto_rawDescData)
	})
	return file_api_flights_api_flights_proto_rawDescData
}

var file_api_flights_api_flights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_flights_api_flights_proto_goTypes = []interface{}{
	(*GetFlightRequest)(nil),    // 0: airbooking.flights_api.GetFlightRequest
	(*ListFlightsResponse)(nil), // 1: airbooking.flights_api.ListFlightsResponse
	(*GetFlightResponse)(nil),   // 2: airbooking.flights_api.GetFlightResponse
	(*models.Flight)(nil),       // 3: airbooking.models.Flight
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_api_flights_api_flights_proto_depIdxs = []int32{
	3, // 0: airbooking.flights_api.ListFlightsResponse.flights:type_name -> airbooking.models.Flight
	3, // 1: airbooking.flights_api.GetFlightResponse.flight:type_name -> airbooking.models.Flight
	4, // 2: airbooking.flights_api.FlightsService.ListFlights:input_type -> google.protobuf.Empty
	0, // 3: airbooking.flights_api.FlightsService.GetFlight:input_type -> airbooking.flights_api.GetFlightRequest
	1, // 4: airbooking.flights_api.FlightsService.ListFlights:output_type -> airbooking.flights_api.ListFlightsResponse
	2, // 5: airbooking.flights_api.FlightsService.GetFlight:output_type -> airbooking.flights_api.GetFlightResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_flights_api_flights_proto_init() }
func file_api_flights_api_flights_proto_init() {
	if File_api_flights_api_flights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_flights_api_flights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_flights_api_flights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFlightsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_flights_api_flights_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_flights_api_flights_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_flights_api_flights_proto_goTypes,
		DependencyIndexes: file_api_flights_api_flights_proto_depIdxs,
		MessageInfos:      file_api_flights_api_flights_proto_msgTypes,
	}.Build()
	File_api_flights_api_flights_proto = out.File
	file_api_flights_api_flights_proto_rawDesc = nil
	file_api_flights_api_flights_proto_goTypes = nil
	file_api_flights_api_flights_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlightsServiceClient is the client API for FlightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlightsServiceClient interface {
	ListFlights(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFlightsResponse, error)
	GetFlight(ctx context.Context, in *GetFlightRequest, opts ...grpc.CallOption) (*GetFlightResponse, error)
}

type flightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightsServiceClient(cc grpc.ClientConnInterface) FlightsServiceClient {
	return &flightsServiceClient{cc}
}

func (c *flightsServiceClient) ListFlights(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFlightsResponse, error) {
	out := new(ListFlightsResponse)
	err := c.cc.Invoke(ctx, "/airbooking.flights_api.FlightsService/ListFlights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightsServiceClient) GetFlight(ctx context.Context, in *GetFlightRequest, opts ...grpc.CallOption) (*GetFlightResponse, error) {
	out := new(GetFlightResponse)
	err := c.cc.Invoke(ctx, "/airbooking.flights_api.FlightsService/GetFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightsServiceServer is the server API for FlightsService service.
type FlightsServiceServer interface {
	ListFlights(context.Context, *emptypb.Empty) (*ListFlightsResponse, error)
	GetFlight(context.Context, *GetFlightRequest) (*GetFlightResponse, error)
}

// UnimplementedFlightsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlightsServiceServer struct {
}

func (*UnimplementedFlightsServiceServer) ListFlights(context.Context, *emptypb.Empty) (*ListFlightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlights not implemented")
}
func (*UnimplementedFlightsServiceServer) GetFlight(context.Context, *GetFlightRequest) (*GetFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlight not implemented")
}

func RegisterFlightsServiceServer(s *grpc.Server, srv FlightsServiceServer) {
	s.RegisterService(&_FlightsService_serviceDesc, srv)
}

func _FlightsService_ListFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightsServiceServer).ListFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbooking.flights_api.FlightsService/ListFlights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightsServiceServer).ListFlights(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightsService_GetFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightsServiceServer).GetFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbooking.flights_api.FlightsService/GetFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightsServiceServer).GetFlight(ctx, req.(*GetFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlightsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "airbooking.flights_api.FlightsService",
	HandlerType: (*FlightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlights",
			Handler:    _FlightsService_ListFlights_Handler,
		},
		{
			MethodName: "GetFlight",
			Handler:    _FlightsService_GetFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/flights_api/flights.proto",
}
